apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-event
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  destination:
    server: https://kubernetes.default.svc
  project: blog
  source:
    repoURL: https://github.com/miyamo2/manifest.miyamo.today.git
    targetRevision: main
    path: 'apps/eventtriggerauth'
  syncPolicy:
    automated: {}