apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-event
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/miyamo2/manifest.miyamo.today.git
    targetRevision: main
    path: 'apps/event'
  syncPolicy:
    automated: {}