apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: blog
    server: https://kubernetes.default.svc
  project: blog
  source:
    repoURL: https://github.com/miyamo2/manifest.miyamo.today.git
    targetRevision: main
    path: 'argo-installs'
  syncPolicy:
    automated: {}