apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: read-model-updater-trigger-auth-aws-credentials
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: secret-aws-credentials
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: secret-aws-credentials
      key: AWS_SECRET_ACCESS_KEY
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: read-model-updater
spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - name: read-model-updater
            image: ghcr.io/miyamo2/blogapi.miyamo.today:read-model-updater-7f83afe0354d4e44c1fb9a6bc52a1c43bb3107c9
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: secret-read-model-updater
              - secretRef:
                  name: secret-aws-credentials
        restartPolicy: Never
    backoffLimit: 4
  pollingInterval: 10 # Optional. Default: 30 seconds
  maxReplicaCount: 30 # Optional. Default: 100
  successfulJobsHistoryLimit: 3 # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 2 # Optional. Default: 100. How many failed jobs should be kept.
  triggers:
    - type: aws-dynamodb
      authenticationRef:
        name: read-model-updater-trigger-auth-aws-credentials
      metadata:
        awsRegion: ap-northeast-1
        tableName: blogging_events-prd
        shardCount: "2"
