apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: read-model-updater-trigger-auth-aws-credentials
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: secret-aws-credentials
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: secret-aws-credentials
      key: AWS_SECRET_ACCESS_KEY
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: read-model-updater-scaledobject
spec:
  scaleTargetRef:
    name: read-model-updater
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURLFromEnv: QUEUE_URL
        queueLength: "5"
        awsRegion: ap-northeast-1
      authenticationRef:
        name: read-model-updater-trigger-auth-aws-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: read-model-updater
  name: read-model-updater
spec:
  replicas: 0
  selector:
    matchLabels:
      app: read-model-updater
  template:
    metadata:
      labels:
        app: read-model-updater
    spec:
      containers:
        - name: read-model-updater
          image: ghcr.io/miyamo2/blogapi.miyamo.today:read-model-updater-4c8eb645842d062511fedbc1369f3df7af66c606
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: secret-read-model-updater
            - secretRef:
                name: secret-aws-credentials
