apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: read-model-updater
  name: read-model-updater
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: read-model-updater
  template:
    metadata:
      labels:
        app: read-model-updater
    spec:
      containers:
        - name: read-model-updater
          image: ghcr.io/miyamo2/blogapi.miyamo.today:read-model-updater-0497a8780451053d8bc9e95ebc86cb63ea2271c9
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: secret-read-model-updater
            - secretRef:
                name: secret-aws-credentials
