apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: read-model-updater
  name: read-model-updater
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: read-model-updater
  template:
    metadata:
      labels:
        app: read-model-updater
    spec:
      containers:
        - name: read-model-updater
          image: ghcr.io/miyamo2/blogapi.miyamo.today:read-model-updater-15252bf0a5eabc91e05740b480a53bb85f39681c
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128Mi
              cpu: 32m
            requests:
              cpu: 20m
          envFrom:
            - secretRef:
                name: secret-read-model-updater
            - secretRef:
                name: secret-aws-credentials
