apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: read-model-updater-trigger-auth-aws-credentials
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: secret-aws-credentials
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: secret-aws-credentials
      key: AWS_SECRET_ACCESS_KEY
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: read-model-updater
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    template:
      spec:
        containers:
          - name: read-model-updater
            image: ghcr.io/miyamo2/blogapi.miyamo.today:read-model-updater-68c7d9e47f9d5ab9f6ad9394fc7d8734760259c9
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: secret-read-model-updater
              - secretRef:
                  name: secret-aws-credentials
        restartPolicy: Never
    backoffLimit: 4
  pollingInterval: 60 # Optional. Default: 30 seconds
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 3 # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 2 # Optional. Default: 100. How many failed jobs should be kept.
  triggers:
    - type: aws-dynamodb-streams
      authenticationRef:
        name: read-model-updater-trigger-auth-aws-credentials
      metadata:
        awsRegion: ap-northeast-1
        tableName: blogging_events-prod
        shardCount: "2"
