apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: article-service
  name: article-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app: article-service
    spec:
      containers:
        - image: us-west1-docker.pkg.dev/blogapi-miyamo-today/article-service/article-service:3683de60050705d221d6a1487c6a3cc29cec852e
          name: article-service
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 128Mi
              cpu: 32m
            requests:
              cpu: 20m
          readinessProbe:
            grpc:
              port: 80
          livenessProbe:
            grpc:
              port: 80
          startupProbe:
            grpc:
              port: 80
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: secret-article-service
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: article-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: article-service
  name: article-service
spec:
  ports:
    - port: 80
  selector:
    app: article-service
  type: ClusterIP
# secret example
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-article-service
# data:
#   COCKROACHDB_DSN: foo
#   SERVICE_NAME: bar
#   NEW_RELIC_CONFIG_APP_NAME: baz
#   NEW_RELIC_CONFIG_LICENSE_KEY: qux
#   PORT: foobar
