apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blogging-event-service
  name: blogging-event-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogging-event-service
  template:
    metadata:
      labels:
        app: blogging-event-service
    spec:
      containers:
        - image: ghcr.io/miyamo2/blogapi.miyamo.today:blogging-event-service-ba972410e59ee63cffc4e88c4eb0c2eacb196b52
          name: blogging-event-service
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 128Mi
              cpu: 32m
            requests:
              cpu: 20m
          readinessProbe:
            grpc:
              port: 80
          livenessProbe:
            grpc:
              port: 80
          startupProbe:
            grpc:
              port: 80
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: secret-blogging-event-service
            - secretRef:
                name: secret-aws-credentials
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: blogging-event-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blogging-event-service
  name: blogging-event-service
spec:
  ports:
    - port: 80
  selector:
    app: blogging-event-service
  type: ClusterIP
# secret example
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-blogging-event-service
# data:
#   SERVICE_NAME: bar
#   NEW_RELIC_CONFIG_APP_NAME: baz
#   NEW_RELIC_CONFIG_LICENSE_KEY: qux
#   PORT: foobar
#   BLOGGING_EVENTS_TABLE_NAME: foo
#   S3_BUCKET: bar
#   CDN_HOST: baz
