apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tag-service
  name: tag-service
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tag-service
  template:
    metadata:
      labels:
        app: tag-service
    spec:
      containers:
        - image: ghcr.io/miyamo2/blogapi.miyamo.today:tag-service-e9f8b9d9908b858b3dd750b0c144f0f89cebbd12
          name: tag-service
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 128Mi
              cpu: 32m
            requests:
              cpu: 20m
          readinessProbe:
            grpc:
              port: 80
          livenessProbe:
            grpc:
              port: 80
          startupProbe:
            grpc:
              port: 80
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: secret-tag-service
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: tag-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tag-service
  name: tag-service
  namespace: blog
spec:
  ports:
    - port: 80
  selector:
    app: tag-service
  type: ClusterIP
# secret example
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-tag-service
# data:
#   COCKROACHDB_DSN: foo
#   SERVICE_NAME: bar
#   NEW_RELIC_CONFIG_APP_NAME: baz
#   NEW_RELIC_CONFIG_LICENSE_KEY: qux
#   PORT: foobar
