apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: federator
  name: federator
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: federator
  template:
    metadata:
      labels:
        app: federator
    spec:
      containers:
        - image: ghcr.io/miyamo2/blogapi.miyamo.today:federator-e9f8b9d9908b858b3dd750b0c144f0f89cebbd12
          name: federator
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 128Mi
              cpu: 64m
            requests:
              cpu: 20m
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: secret-federator
            - secretRef:
                name: secret-aws-credentials
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: federator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: federator
  name: federator
  namespace: blog
spec:
  ports:
    - port: 80
  selector:
    app: federator
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: federator
  namespace: blog
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  ingressClassName: "cloudflare"
  rules:
    - host: "blogapi.miyamo.today"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: federator
                port:
                  number: 80
# secret example
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-federator
# data:
#   NEW_RELIC_CONFIG_APP_NAME: foo
#   NEW_RELIC_CONFIG_LICENSE: bar
#   ARTICLE_SERVICE_ADDRESS: baz
#   TAG_SERVICE_ADDRESS: qux
#   BLOGGING_EVENT_SERVICE_ADDRESS: foobar
#   PORT: foobaz
