name: CD

on:
  repository_dispatch:
    types:
      - article-service
      - tag-service
      - blogging-event-service
      - federator

permissions: write-all

concurrency:
  group: ${{ github.workflow }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Tag
        id: get_tag
        run: |
          TAG=$(echo ${{ github.event.client_payload.tag }})
          echo "tag=$TAG" >> $GITHUB_ENV

      - if: github.event.client_payload.target == 'article-service'
        run: echo "file=apps/microservice/article-service.yaml" >> $GITHUB_ENV

      - if: github.event.client_payload.target == 'tag-service'
        run: echo "file=apps/microservice/tag-service.yaml" >> $GITHUB_ENV

      - if: github.event.client_payload.target == 'blogging-event-service'
        run: echo "file=apps/microservice/blogging-event-service.yaml" >> $GITHUB_ENV

      - if: github.event.client_payload.target == 'federator'
        run: echo "file=apps/federator/federator.yaml" >> $GITHUB_ENV

      - name: Update tag
        env:
          IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.client_payload.target }}/${{ github.event.client_payload.target }}:${{ env.tag }}
        uses: mikefarah/yq@8bf425b4d1344db7cd469a8d10a390876e0c77fd # v4.45.1
        with:
          cmd: yq eval -i '(. | select(.kind == "Deployment") | .spec.template.spec.containers[] | select(.name == "${{ github.event.client_payload.target }}").image) = "${{ env.IMAGE }}"' ${{ env.file }}

      - name: commit
        env:
          TAG: ${{ env.tag }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./apps
          commit_message="chore(${{ env.file }}): bump tag to ${{ env.TAG }}"
          git commit -m "$commit_message"
          git push origin HEAD:main
