name: CD

on:
  repository_dispatch:
    types:
      - article-service
      - tag-service
      - blogging-event-service
      - federator

permissions: write-all

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Tag
        id: get_tag
        run: |
          TAG=$(echo ${{ github.event.client_payload.tag }})
          echo "tag=$TAG" >> GITHUB_OUTPUT

      - name: Get File
        id: get_file
        run: |
          TARGET=$(echo ${{ github.event.client_payload.target }})
          if [ "$TARGET" = "article-service"]; then
            echo "file=apps/microservice/article-service.yaml" >> $GITHUB_OUTPUT
            exit 0
          if [ "$TARGET" = "tag-service"]; then
            echo "file=apps/microservice/tag-service.yaml" >> $GITHUB_OUTPUT
            exit 0
          if [ "$TARGET" = "blogging-event-service"]; then
            echo "file=apps/microservice/blogging-event-service.yaml" >> $GITHUB_OUTPUT
            exit 0
          if [ "$TARGET" = "federator"]; then
            echo "file=apps/federator/federator.yaml" >> $GITHUB_OUTPUT

      - name: Update tag
        env:
          REPOSITORY: ${{ github.event.client_payload.target }}
          IMAGE_NAME: ${{ github.event.client_payload.image_name }}
          TAG: ${{ steps.get_tag.outputs.tag }}
          TARGET_FILE: ${{ steps.get_file.outputs.file }}
        uses: mikefarah/yq@8bf425b4d1344db7cd469a8d10a390876e0c77fd # v4.45.1
        with:
          cmd: IMAGE_TAG=' ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}' yq eval '.containers[].image = env(IMAGE_TAG)' -i ${{ env.TARGET_FILE }}

      - name: commit
        env:
          TAG: ${{ steps.get_tag.outputs.tag }}
          TARGET_FILE: ${{ steps.get_file.outputs.file }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./apps
          git commit -m "chore(${{ env.TARGET_FILE }}): bump tag to ${{ env.TAG }}"
          git push origin HEAD:main
